Allow Runtime Configuration
KamilLelonek/ex_postmark pull request #3
Opened 2017-02-20 17:56 UTC by maennchen

The Configuration is written in the using macro. This way this lib can't be configured via distillery.

This PR fixes this issue.

2017-02-21 12:03 UTC, KamilLelonek commented
I really like this change. The only thing to do here is to align the code to make it consistent across the entire codebase.

2017-02-21 12:16 UTC, maennchen commented
Can you tell me what exactly you'd like to change?

2017-02-21 12:19 UTC, KamilLelonek commented
I added two sample changes. There are a couple of places more with this possible modification.

2017-02-22 15:16 UTC, KamilLelonek requested changes

2017-02-22 15:16 UTC, KamilLelonek commented on lib/ex_postmark/mailer.ex
> +      {key, value} -> {key, value}
```elixir
{key, {:system, env_var}}          -> {key, System.get_env(env_var)}
{key, {:system, env_var, default}} -> {key, System.get_env(env_var) || default}
{key, value}                       -> {key, value}
```

2017-02-22 15:16 UTC, KamilLelonek commented on test/ex_postmark/mailer_test.exs
> +          replace_with_default_not_empty: config[:replace_with_default_not_empty]
```elixir
replace_without_default_empty:     config[:replace_without_default_empty],
replace_with_default_empty:        config[:replace_with_default_empty],
replace_without_default_not_empty: config[:replace_without_default_not_empty],
replace_with_default_not_empty:    config[:replace_with_default_not_empty]
```

2017-02-22 15:33 UTC, maennchen commented
@KamilLelonek I'm not used to indenting things like that. Is it ok now?

2017-02-22 15:37 UTC, maennchen commented
@KamilLelonek If you are still not ok with the changes, I propose you do it yourself directly.

I set the `Allow edits from maintainers.` flag to true so you have write permissions. This'll be faster I think ;)

2017-02-22 15:47 UTC, KamilLelonek commented
It looks awesome! Don't you think so?

Please merge master to your PR as well because there are build errors.

2017-02-22 16:45 UTC, maennchen commented
I really don't like this indention style. Not because it looks bad, but because if I introduce a new longer variable, I have changes on the unchanged lines as well.

2017-02-22 16:51 UTC, maennchen commented
It is already on master. I just did a rebase.

The errors originate from `ExPostmark.Integration.TestPostmark`. I think that those errors are caused by missing env variables in the integration tests.

I would advise to move this snippet into a `setup` method:

```
Email.new(
    subject:        "Hello from TravisCI",
    from:           @postmark_email_from,
    to:             @postmark_email_to,
    template_id:    @postmark_template_id,
    template_model: %{name: "TravisCI", product_name: "ExPostmark"}
  )
```

2017-02-22 16:52 UTC, KamilLelonek commented
Integration tests are disabled on master.

2017-02-22 16:52 UTC, KamilLelonek commented
https://github.com/KamilLelonek/ex_postmark/commit/db2ef2e266a6f8ef1b6cafb11510317760384f1d

2017-02-22 16:53 UTC, maennchen commented
I know, but the code around the test gets executed anyway....

2017-02-22 16:54 UTC, KamilLelonek commented
Env variables are properly set on TravisCI, moreover master branch build passes.

2017-02-22 16:55 UTC, maennchen commented
Yes, but not if travis builds PR's on my repo. Otherwise I could just modify the code to spill your postmark key ;-)

2017-02-22 16:56 UTC, maennchen commented
If I do `mix test` on master without any Env Variables I get this:

```
Excluding tags: [:integration]

.....................** (ArgumentError) The recipient `nil` is invalid.
Recipients must be a string representing an email address
like `foo.bar@example.com` or a two-element tuple `{name, address}`,
where name and address are strings.

    (ex_postmark) lib/ex_postmark/formatter.ex:19: ExPostmark.Formatter.raise_invalid_recipient/1
    (ex_postmark) lib/ex_postmark/email.ex:200: ExPostmark.Email.from/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    test/integration/postmark_test.exs:13: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:370: Code.require_file/2
```

If I apply this PATCH, it works:

```patch
diff --git a/test/integration/postmark_test.exs b/test/integration/postmark_test.exs
index d8c02dd..0d19999 100644
--- a/test/integration/postmark_test.exs
+++ b/test/integration/postmark_test.exs
@@ -10,13 +10,18 @@ defmodule ExPostmark.Integration.TestPostmark do
   @postmark_email_from  System.get_env("POSTMARK_EMAIL_FROM")
   @postmark_email_to    System.get_env("POSTMARK_EMAIL_TO")
 
-  @email Email.new(
-    subject:        "Hello from TravisCI",
-    from:           @postmark_email_from,
-    to:             @postmark_email_to,
-    template_id:    @postmark_template_id,
-    template_model: %{name: "TravisCI", product_name: "ExPostmark"}
-  )
+  setup do
+
+    email = Email.new(
+      subject:        "Hello from TravisCI",
+      from:           @postmark_email_from,
+      to:             @postmark_email_to,
+      template_id:    @postmark_template_id,
+      template_model: %{name: "TravisCI", product_name: "ExPostmark"}
+    )
+
+    {:ok, email: email}
+  end
 
   Application.put_env(
     :ex_postmark,   ExPostmark.Integration.TestPostmark.PostmarkMailer,
@@ -28,7 +33,7 @@ defmodule ExPostmark.Integration.TestPostmark do
     use ExPostmark.Mailer, otp_app: :ex_postmark
   end
 
-  test "should deliver a template email using Postmark service" do
-    assert {:ok, %{id: _id}} = PostmarkMailer.deliver(@email)
+  test "should deliver a template email using Postmark service", %{email: email} do
+    assert {:ok, %{id: _id}} = PostmarkMailer.deliver(email)
   end
 end
```

2017-02-22 16:58 UTC, merged

2017-02-22 16:58 UTC, maennchen commented
I'll make another PR with changes, so that it works without env variables too.